rvm:
  - 2.2
  - 2.3
  - 2.4.5
  - 2.5.3
  - 2.6.0
  - ruby-head

os:
  - linux
  - osx

dist: trusty

gemfile:
  - Gemfile

before_install:
  - gem update --system=2.7.8

script: bundle exec rake test

matrix:
  allow_failures:
    - rvm: ruby-head
